services:
  api:
    build: .
    container_name: muni-api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://charlie.c:${POSTGRES_PASSWORD}@db:5432/transit
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  db:
    image: postgis/postgis:15-3.3
    container_name: muni-db
    environment:
      POSTGRES_USER: charlie.c
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: transit
      POSTGRES_HOST = postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U charlie.c -d transit"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  fetcher:
    build: .
    container_name: muni-gtfs-fetcher
    environment:
      GTFS_API_KEY: 5e6bf5d8-1d98-4eb3-b927-69dcab843474
      DATABASE_URL: postgresql://charlie.c:${POSTGRES_PASSWORD}@db:5432/transit
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    command: python fetch_data_loop.py
  
volumes:
  pgdata:
